### ISSUE TITLE
Installation / adding event listener

### ISSUE THREAD

**Issue by derbra1513** [ClipboardHealth/capacitor-firebase-dynamic-links#3]
Hello and thank you for the work on the plugin. I apologize as I am still learning Ionic/Capacitor. But I am having trouble installing and retrieving the URL. Here is what I did so far.

1. Installed via CLI using **npm i @clipboardhealth/capacitor-firebase-dynamic-links**
2. added the following code to my app.component.ts file
3. I have a feeling I am not initiating the plugin correctly, however I do know it is installed correctly as I can add a print(url) inside the plugin.swift file and the url does display.

Any help on how to properly install the plugin and add the listener to retrieve the URL would be greatly appreciated!

`import { Component } from '@angular/core';

import {  CapacitorFirebaseDynamicLinksPlugin } from '@clipboardhealth/capacitor-firebase-dynamic-links'

import { Platform, NavController } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss']
})
export class AppComponent {
  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar,
    public navCtrl: NavController,
    public csl: CapacitorFirebaseDynamicLinksPlugin
  ) {
    this.initializeApp();
  }
  
  initializeApp() {
    this.csl.addListener('deepLinkOpen', (data) => {
      console.log('Dynamic Link = ' + data.url);
    })
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
    });

  }
}
`

**Comment by oliverandersencox** [comment]
@derbra1513 did you figure this out?

**Comment by oliverandersencox** [comment]
`const { SplashScreen, App, Browser, StatusBar, CapacitorFirebaseDynamicLinksPlugin } = Plugins;`

```
  CapacitorFirebaseDynamicLinksPlugin.addListener("deepLinkOpen", (data: any) => {
        console.log('ANDROID FIREBASE DYNAMIC LINK OPENED');
        console.log(data);
      })
```

**Comment by derbra1513** [comment]
@oliverandersencox Thank you very much this worked, this is basic implementation for capacitor plugins, I did not realize at the time. Documentation would be great for novices like myself.

**Comment by oliverandersencox** [comment]
this plugin crashes on opening the app on android :/

**Comment by shakeelshahzad** [comment]
I will be working on the readme file to update the documentation.
